
# Phase 3: Comparison Table (LaTeX)
# Produces a table comparing LP-IV IRFs across three samples at
# selected horizons: h = 0, 3, 6, 9, 12.
# Columns: EMU20 | EU27 | EU7 Placebo
# Each cell: point estimate with 90% CI below in parentheses.
# Bottom panel: KP F-statistic.
# Run from the code/ directory.

library(readr)
library(dplyr)

out_dir <- "../output/tables"

# ── Load IRF CSVs ──────────────────────────────────────────────────────────────
emu20 <- read_csv(file.path(out_dir, "irf_emu20.csv"), show_col_types=FALSE)
comp  <- read_csv(file.path(out_dir, "irf_eu27_comparison.csv"), show_col_types=FALSE)
eu7   <- read_csv(file.path(out_dir, "irf_eu7_placebo.csv"), show_col_types=FALSE)

horizons <- c(0, 3, 6, 9, 12)

fmt_cell <- function(b, lo, hi) {
  sprintf("%.3f [%.3f, %.3f]", b, lo, hi)
}

fmt_tex <- function(b, lo, hi) {
  sprintf("$%.3f$\\\\ \\footnotesize{$[%.3f,\\;%.3f]$}", b, lo, hi)
}

# ── Select horizons ────────────────────────────────────────────────────────────
e20 <- emu20 %>% filter(Months %in% horizons) %>%
  select(h = Months, b, lo = d90, hi = u90, f = Fstat)

eu27_e <- comp %>% filter(Months %in% horizons) %>%
  select(h = Months,
         b_20 = b_emu20, lo_20 = d90_emu20, hi_20 = u90_emu20, f_20 = Fstat_emu20,
         b_27 = b_eu27,  lo_27 = d90_eu27,  hi_27 = u90_eu27,  f_27 = Fstat_eu27)

eu7p <- eu7 %>% filter(Months %in% horizons) %>%
  select(h = Months, b_eu7 = b, lo_eu7 = d90, hi_eu7 = u90, f_eu7 = Fstat)

# ── Build LaTeX table ──────────────────────────────────────────────────────────
tex <- c(
  "% Phase 3 comparison table — generated by code/6.3_phase3_table.R",
  "\\begin{table}[htbp]",
  "\\centering",
  "\\caption{Second-Round Pass-Through: Baseline Replication and EU27 Extension}",
  "\\label{tab:phase3_comparison}",
  "{\\small",
  "\\begin{tabular}{lccc}",
  "\\toprule",
  " & EMU20 & EU27 & EU7 Placebo \\\\",
  "\\midrule",
  "\\multicolumn{4}{l}{\\textit{Panel A: Point estimates (90\\% CI)}} \\\\[4pt]"
)

for (h in horizons) {
  r20  <- e20[e20$h == h, ]
  r27  <- eu27_e[eu27_e$h == h, ]
  r7   <- eu7p[eu7p$h == h, ]

  cell20 <- sprintf("$%.3f$", r20$b)
  cell27 <- sprintf("$%.3f$", r27$b_27)
  cell7  <- sprintf("$%.3f$", r7$b_eu7)

  ci20 <- sprintf("\\footnotesize{$[%.3f,\\;%.3f]$}", r20$lo, r20$hi)
  ci27 <- sprintf("\\footnotesize{$[%.3f,\\;%.3f]$}", r27$lo_27, r27$hi_27)
  ci7  <- sprintf("\\footnotesize{$[%.3f,\\;%.3f]$}", r7$lo_eu7, r7$hi_eu7)

  tex <- c(tex,
    sprintf("$h=%d$ & %s & %s & %s \\\\", h, cell20, cell27, cell7),
    sprintf("      & %s & %s & %s \\\\[2pt]", ci20, ci27, ci7)
  )
}

tex <- c(tex,
  "\\midrule",
  "\\multicolumn{4}{l}{\\textit{Panel B: First-stage diagnostics}} \\\\[4pt]",
  sprintf("KP $F$-statistic & $%.1f$ & $%.1f$ & $%.1f$ \\\\",
          e20$f[1], eu27_e$f_27[1], eu7p$f_eu7[1]),
  "Countries & 20 & 27 & 7 \\\\",
  "\\bottomrule",
  "\\end{tabular}",
  "}",
  "\\begin{tablenotes}[flushleft]",
  "\\footnotesize",
  "\\item \\textit{Notes:} LP-IV estimates of the tradable-to-non-tradable",
  "inflation pass-through coefficient $\\theta_h$ at selected horizons.",
  "Bartik IV: $Z_{it} = w^{\\text{trad}}_{it} \\times Z^{\\text{BH}}_t$.",
  "Controls: 12 lags of non-tradable inflation, tradable inflation,",
  "unemployment rate, and log NEER change. Country FE. vce(robust).",
  "90\\% confidence intervals in brackets. KP $F$-statistic uniform",
  "across horizons by construction of the Bartik instrument.",
  "EU7 NEER: bilateral EUR spot rate (ECB EXR).",
  "\\end{tablenotes}",
  "\\end{table}"
)

writeLines(tex, file.path(out_dir, "tab_phase3_comparison.tex"))
cat("LaTeX table saved: output/tables/tab_phase3_comparison.tex\n")

# ── Print readable summary ─────────────────────────────────────────────────────
cat("\n=== PHASE 3 RESULTS SUMMARY ===\n\n")
cat(sprintf("%-5s  %-22s  %-22s  %-22s\n",
            "h", "EMU20", "EU27", "EU7 Placebo"))
cat(strrep("-", 75), "\n")
for (h in horizons) {
  r20 <- e20[e20$h == h, ]
  r27 <- eu27_e[eu27_e$h == h, ]
  r7  <- eu7p[eu7p$h == h, ]
  cat(sprintf("%-5d  %-22s  %-22s  %-22s\n", h,
    fmt_cell(r20$b, r20$lo, r20$hi),
    fmt_cell(r27$b_27, r27$lo_27, r27$hi_27),
    fmt_cell(r7$b_eu7, r7$lo_eu7, r7$hi_eu7)))
}
cat(strrep("-", 75), "\n")
cat(sprintf("KP F: EMU20 = %.1f | EU27 = %.1f | EU7 = %.1f\n",
            e20$f[1], eu27_e$f_27[1], eu7p$f_eu7[1]))
