
# Phase 4: Instrument Robustness Table (LaTeX)
# Produces a comparison table with three columns:
#   BH (baseline) | IMF non-fuel | GSCPI (diagnostic — fails weak IV)
# GSCPI is included as a diagnostic note only; the main robustness columns
# are BH and IMF non-fuel.
# BDI: unavailable (FRED series unavailable, documented in Phase 2).
# Run from the code/ directory.

suppressMessages(library(readr))
suppressMessages(library(dplyr))

out_dir <- "../output/tables"

# ── Load IRF CSV ───────────────────────────────────────────────────────────────
irf <- read_csv(file.path(out_dir, "irf_rob_instruments.csv"), show_col_types = FALSE)

horizons <- c(0, 3, 6, 9, 12)

# ── Readable summary ──────────────────────────────────────────────────────────
cat("=== PHASE 4 RESULTS SUMMARY ===\n\n")
cat(sprintf("%-5s  %-22s  %-22s  %-22s\n", "h", "BH (baseline)", "IMF non-fuel", "GSCPI (WEAK)"))
cat(strrep("-", 75), "\n")

fmt_cell <- function(b, lo, hi) sprintf("%.3f [%.3f, %.3f]", b, lo, hi)

for (h in horizons) {
  r <- irf[irf$Months == h, ]
  cat(sprintf("%-5d  %-22s  %-22s  %-22s\n", h,
    fmt_cell(r$b_bh,    r$d90_bh,       r$u90_bh),
    fmt_cell(r$b_imf,   r$d90_imf,      r$u90_imf),
    fmt_cell(r$b_gscpi, r$d90_gscpi,    r$u90_gscpi)))
}
cat(strrep("-", 75), "\n")
cat(sprintf("KP F: BH = %.1f | IMF = %.1f | GSCPI(Bartik) = %.1f | GSCPI(direct) = %.1f\n",
            irf$Fstat_bh[1], irf$Fstat_imf[1], irf$Fstat_gscpi[1], irf$Fstat_gscpi_d[1]))
cat("\nFLAG: GSCPI fails weak instrument test (KP F < 4). Excluded from table.\n")
cat("FLAG: BDI unavailable (FRED series 404, documented Phase 2).\n\n")

# ── LaTeX table ───────────────────────────────────────────────────────────────
# Two robustness columns: BH and IMF non-fuel
tex <- c(
  "% Phase 4 instrument robustness table — generated by code/7.2_rob_instruments_table.R",
  "\\begin{table}[htbp]",
  "\\centering",
  "\\caption{Instrument Robustness: Alternative IV Specifications}",
  "\\label{tab:rob_instruments}",
  "{\\small",
  "\\begin{tabular}{lcc}",
  "\\toprule",
  " & BH Oil Shock & IMF Non-Fuel \\\\",
  " & (Baseline) & Commodity Shock \\\\",
  "\\midrule",
  "\\multicolumn{3}{l}{\\textit{Panel A: Point estimates (90\\% CI)}} \\\\[4pt]"
)

for (h in horizons) {
  r <- irf[irf$Months == h, ]
  tex <- c(tex,
    sprintf("$h=%d$ & $%.3f$ & $%.3f$ \\\\", h, r$b_bh, r$b_imf),
    sprintf("      & \\footnotesize{$[%.3f,\\;%.3f]$} & \\footnotesize{$[%.3f,\\;%.3f]$} \\\\[2pt]",
            r$d90_bh, r$u90_bh, r$d90_imf, r$u90_imf)
  )
}

tex <- c(tex,
  "\\midrule",
  "\\multicolumn{3}{l}{\\textit{Panel B: First-stage diagnostics}} \\\\[4pt]",
  sprintf("KP $F$-statistic & $%.1f$ & $%.1f$ \\\\", irf$Fstat_bh[1], irf$Fstat_imf[1]),
  "Countries & 20 & 20 \\\\",
  "\\bottomrule",
  "\\end{tabular}",
  "}",
  "\\begin{tablenotes}[flushleft]",
  "\\footnotesize",
  "\\item \\textit{Notes:} LP-IV estimates of the tradable-to-non-tradable",
  "inflation pass-through coefficient $\\theta_h$ at selected horizons.",
  "EMU20 sample. Bartik IV: $Z_{it} = w^{\\text{trad}}_{it} \\times \\text{shock}_t$.",
  "BH: Baumeister-Hamilton oil price expectation shock.",
  "IMF: AR(1) innovations on log-differences of the IMF non-fuel primary",
  "commodity price index (PALLFNFINDEXM via FRED).",
  "Controls: 12 lags of non-tradable inflation, tradable inflation,",
  "unemployment rate, and log NEER change. Country FE. vce(robust).",
  "90\\% confidence intervals in brackets.",
  "GSCPI instrument (AR(2) innovations on the NY Fed Global Supply Chain",
  "Pressure Index, both Bartik-weighted and direct) excluded: KP $F < 4$",
  "in all specifications (weak instrument). BDI: unavailable.",
  "\\end{tablenotes}",
  "\\end{table}"
)

writeLines(tex, file.path(out_dir, "tab_rob_instruments.tex"))
cat("LaTeX table saved: output/tables/tab_rob_instruments.tex\n")
