
# Phase 5: Heterogeneity Table (LaTeX)
# Three-way split of EMU20: Core | Periphery | Small open economies
# Shows point estimates (90% CI) at selected horizons and first-stage diagnostics.
# Pairwise t-statistics from independent-samples test: t = Δb / sqrt(se1² + se2²).
# Run from the code/ directory.

suppressMessages(library(readr))
suppressMessages(library(dplyr))

out_dir <- "../output/tables"

irf <- read_csv(file.path(out_dir, "irf_heterogeneity.csv"), show_col_types = FALSE)

horizons <- c(0, 3, 6, 9, 12)

# ── Readable summary ──────────────────────────────────────────────────────────
cat("=== PHASE 5 RESULTS SUMMARY ===\n\n")
cat(sprintf("%-5s  %-22s  %-22s  %-22s\n", "h", "Core (N=6)", "Periphery (N=4)", "Small open (N=10)"))
cat(strrep("-", 75), "\n")

fmt_cell <- function(b, lo, hi) sprintf("%.3f [%.3f, %.3f]", b, lo, hi)

for (h in horizons) {
  r <- irf[irf$Months == h, ]
  cat(sprintf("%-5d  %-22s  %-22s  %-22s\n", h,
    fmt_cell(r$b_core, r$d90_core, r$u90_core),
    fmt_cell(r$b_peri, r$d90_peri, r$u90_peri),
    fmt_cell(r$b_soe,  r$d90_soe,  r$u90_soe)))
}
cat(strrep("-", 75), "\n")
cat(sprintf("KP F: Core = %.1f | Periphery = %.1f | SOE = %.1f\n",
            irf$Fstat_core[1], irf$Fstat_peri[1], irf$Fstat_soe[1]))

cat("\n--- Pairwise t-statistics (two-sided, N(0,1), critical 1.96) ---\n")
cat(sprintf("%-5s  %12s  %12s  %12s\n", "h", "Core-Peri", "Core-SOE", "Peri-SOE"))
for (h in horizons) {
  r <- irf[irf$Months == h, ]
  t_cp <- (r$b_core - r$b_peri) / sqrt(r$se_core^2 + r$se_peri^2)
  t_cs <- (r$b_core - r$b_soe)  / sqrt(r$se_core^2 + r$se_soe^2)
  t_ps <- (r$b_peri - r$b_soe)  / sqrt(r$se_peri^2 + r$se_soe^2)
  sig_cp <- ifelse(abs(t_cp) > 1.96, "*", " ")
  sig_cs <- ifelse(abs(t_cs) > 1.96, "*", " ")
  sig_ps <- ifelse(abs(t_ps) > 1.96, "*", " ")
  cat(sprintf("%-5d  %6.2f%s       %6.2f%s       %6.2f%s\n",
              h, t_cp, sig_cp, t_cs, sig_cs, t_ps, sig_ps))
}
cat("* p < 0.05 (two-sided)\n\n")
cat("NOTE: No pairwise difference is significant at 5%. Periphery shows\n")
cat("      systematically larger estimates at h=3-6 but wide CIs (N=4).\n\n")

# ── LaTeX table ───────────────────────────────────────────────────────────────
tex <- c(
  "% Phase 5 heterogeneity table — generated by code/8.1_heterogeneity_table.R",
  "\\begin{table}[htbp]",
  "\\centering",
  "\\caption{Second-Round Pass-Through: Heterogeneity Across EMU Groups}",
  "\\label{tab:heterogeneity}",
  "{\\small",
  "\\begin{tabular}{lccc}",
  "\\toprule",
  " & Core & Periphery & Small Open \\\\",
  " & (N=6) & (N=4) & (N=10) \\\\",
  "\\midrule",
  "\\multicolumn{4}{l}{\\textit{Panel A: Point estimates (90\\% CI)}} \\\\[4pt]"
)

for (h in horizons) {
  r <- irf[irf$Months == h, ]
  tex <- c(tex,
    sprintf("$h=%d$ & $%.3f$ & $%.3f$ & $%.3f$ \\\\", h, r$b_core, r$b_peri, r$b_soe),
    sprintf("      & \\footnotesize{$[%.3f,\\;%.3f]$} & \\footnotesize{$[%.3f,\\;%.3f]$} & \\footnotesize{$[%.3f,\\;%.3f]$} \\\\[2pt]",
            r$d90_core, r$u90_core, r$d90_peri, r$u90_peri, r$d90_soe, r$u90_soe)
  )
}

# Pairwise t-stats panel
tex <- c(tex,
  "\\midrule",
  "\\multicolumn{4}{l}{\\textit{Panel B: Pairwise group-difference $t$-statistics}} \\\\[4pt]",
  " & Core$-$Peri & Core$-$SOE & Peri$-$SOE \\\\"
)
for (h in horizons) {
  r <- irf[irf$Months == h, ]
  t_cp <- (r$b_core - r$b_peri) / sqrt(r$se_core^2 + r$se_peri^2)
  t_cs <- (r$b_core - r$b_soe)  / sqrt(r$se_core^2 + r$se_soe^2)
  t_ps <- (r$b_peri - r$b_soe)  / sqrt(r$se_peri^2 + r$se_soe^2)
  tex <- c(tex,
    sprintf("$h=%d$ & $%.2f$ & $%.2f$ & $%.2f$ \\\\[2pt]",
            h, t_cp, t_cs, t_ps))
}

tex <- c(tex,
  "\\midrule",
  "\\multicolumn{4}{l}{\\textit{Panel C: First-stage diagnostics}} \\\\[4pt]",
  sprintf("KP $F$-statistic & $%.1f$ & $%.1f$ & $%.1f$ \\\\",
          irf$Fstat_core[1], irf$Fstat_peri[1], irf$Fstat_soe[1]),
  "\\bottomrule",
  "\\end{tabular}",
  "}",
  "\\begin{tablenotes}[flushleft]",
  "\\footnotesize",
  "\\item \\textit{Notes:} LP-IV estimates of $\\theta_h$ at selected horizons.",
  "Core: DEU, FRA, NLD, AUT, FIN, BEL.",
  "Periphery: ITA, ESP, PRT, GRC.",
  "Small open: IRL, LUX, EST, LVA, LTU, SVK, SVN, MLT, CYP, HRV.",
  "Bartik IV: $Z_{it} = w^{\\text{trad}}_{it} \\times Z^{\\text{BH}}_t$.",
  "Controls: 12 lags of non-tradable inflation, tradable inflation,",
  "unemployment rate, and log NEER change. Country FE. vce(robust).",
  "90\\% confidence intervals in brackets.",
  "Panel B: pairwise $t$-statistics under independent samples,",
  "$t = (\\hat{\\theta}^{g_1}_h - \\hat{\\theta}^{g_2}_h) \\mathbin{/}",
  "\\sqrt{\\hat{\\sigma}^2_{g_1,h} + \\hat{\\sigma}^2_{g_2,h}}$.",
  "No difference is significant at the 5\\% level.",
  "\\end{tablenotes}",
  "\\end{table}"
)

writeLines(tex, file.path(out_dir, "tab_heterogeneity.tex"))
cat("LaTeX table saved: output/tables/tab_heterogeneity.tex\n")
